# configs/best_config_optuna_100.yaml # Actualizado con los nuevos mejores parámetros

# Rutas (copiar de base_config.yaml)
data_raw_path: "data/raw/"
train_file: "train.csv"
# ...otras rutas... (asumiendo que las tienes en tu base_config.yaml)
data_processed_path: "data/processed/"
models_path: "models/"
metrics_path: "metrics/"
submission_path: "submissions/"
test_file: "test_x.csv" # Asumiendo que también lo tienes

# Columnas a procesar (copiar de base_config.yaml)
numerical_columns:
  - Num_Adultos
  - Num_Niños
  - Noches_Semana
  - Noches_Fin_Semana
  - Tiempo_Antelación
  - Precio_Promedio_Por_Habitación
  - Num_Solicitudes_Especiales

categorical_columns:
  - Tipo_Plan_Comidas
  - Tipo_Habitación_Reservada
  - Segmento_Mercado

# Limpieza y tratamiento de outliers (ACTUALIZADO según Optuna)
preprocessing:
  create_missing_flags: true
  outlier_treatment_numerical: 'none'   # <<< ACTUALIZADO: Optuna eligió 'none'
  # Las siguientes claves de winsor/log ya no son necesarias si es 'none', pero no dañan si se quedan
  # winsor_cols: ['Tiempo_Antelación','Precio_Promedio_Por_Habitación'] # Comentado ya que no aplica
  # log_transform_cols: ['Tiempo_Antelación','Precio_Promedio_Por_Habitación'] # Comentado ya que no aplica
  # winsor_quantiles_lower: 0.01 # Comentado ya que no aplica
  # winsor_quantiles_upper: 0.99 # Comentado ya que no aplica
  categorical_imputation_fill_value: 'Missing'
  rare_grouping_threshold: 0.01 # Optuna no optimizó esto, mantener el valor base o el que usaste

# Identificadores (copiar de base_config.yaml)
id_columns:
  - "Id"
  - "ID_Reserva"
target_column: "Estado_Reserva"
target_positive_class: "Cancelada"   # Mantener para mapeo
target_negative_class: "No Cancelada" # Mantener para mapeo
random_seed: 42 # Mantener o usar el del config base

# Encoding (ACTUALIZADO según Optuna)
encoding:
  method: 'target'        # <<< ACTUALIZADO: Optuna eligió 'target'
  target_smoothing: 11.271975930618606 # <<< ACTUALIZADO según Optuna

# Feature Engineering Params (copiar de base_config.yaml, Optuna no optimizó estos aquí)
feature_engineering_params:
  antelacion_bins: [-1, 0, 7, 30, 90, 180, 10000]
  antelacion_labels: ['0_SameDay', '1_1-7Days', '2_8-30Days', '3_31-90Days', '4_91-180Days', '5_180+Days']
  
  month_to_season_map:
    1: 'Invierno'
    2: 'Invierno'
    3: 'Primavera'
    4: 'Primavera'
    5: 'Primavera'
    6: 'Verano'
    7: 'Verano'
    8: 'Verano'
    9: 'Otoño'
    10: 'Otoño'
    11: 'Otoño'
    12: 'Invierno'

  cols_to_drop_after_fe: # Estas son las columnas ORIGINALES que se dropean después de crear nuevas features a partir de ellas
    - "Num_Adultos"
    - "Num_Niños"
    - "Noches_Semana"
    - "Noches_Fin_Semana"
    # Considera si alguna feature creada en el FE debería dropearse aquí
    # o si el dropeo se gestiona por no estar en numerical/categorical_columns al final.

# Modelo (ACTUALIZADO según Optuna)
model:
  name: 'lightgbm'
  params:
    # Parámetros Fijos (asegúrate que coinciden con los usados en objective)
    objective: 'binary'
    metric: 'binary_logloss' # Métrica interna de entrenamiento
    random_state: 42         # Usar la semilla base
    n_jobs: -1
    verbosity: -1            # Para menos output
    # early_stopping_rounds: 50 # Solo si se usa con eval_set en fit

    # Parámetros Optimizados por Optuna
    boosting_type: 'gbdt'                           # <<< ACTUALIZADO
    n_estimators: 800                               # <<< ACTUALIZADO
    learning_rate: 0.02103308100345942              # <<< ACTUALIZADO
    num_leaves: 123                                 # <<< ACTUALIZADO
    max_depth: 9                                    # <<< ACTUALIZADO
    reg_alpha: 6.509388181112787e-07                # <<< ACTUALIZADO
    reg_lambda: 6.792896299027691e-05               # <<< ACTUALIZADO
    colsample_bytree: 0.4259062560252868            # <<< ACTUALIZADO
    min_child_samples: 7                            # <<< ACTUALIZADO
    min_split_gain: 0.15899938133988173             # <<< ACTUALIZADO
    max_bin: 352                                    # <<< ACTUALIZADO
    subsample: 0.637856332294457                    # <<< ACTUALIZADO (aplica para gbdt)
    subsample_freq: 5                               # <<< ACTUALIZADO (aplica para gbdt si subsample < 1.0)

prediction:
  threshold: 0.47   # Umbral optimizado sobre OOF para maximizar F1-weighted

# CV config (Opcional, si quieres definirlo aquí para run_experiment)
# cv_n_splits: 5